version: '3.9'

services:
  # Our Postgres database
  db: # The service will be named db.
    image: postgres # The postgres image will be used
    restart: always # Always try to restart if this stops running
    environment: # Provide environment variables
      POSTGRES_USER: nest # POSTGRES_USER env var w/ value baloo
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nest
    ports: # Expose ports so that apps not running via docker compose can connect to them.
      - 5000:5000 # format here is "port on our machine":"port on container"

  nestjs-app:
    build: .
    ports:
      - '3000:3000' # Adjust the port as needed
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5000
      - DB_USER=nest
      - DB_PASSWORD=nest
      - DB_DATABASE=nest

  # Adminer provides a nice little web UI to connect to databases
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # Pick a theme - https://github.com/vrana/adminer/tree/master/designs
    ports:
      - 8000:8080
